Генерация формы с помощью FormBuilder
FlawlessTheory/edu pull request #17
Opened 2020-10-05 05:17 UTC by FlawlessTheory

Может, добавлю каких-нибудь валидаторов или ещё чего

2020-10-05 06:01 UTC, nikitamugen requested changes

2020-10-05 06:01 UTC, nikitamugen commented on src/app/components/definition-tab/definition-tab-input-form/definition-tab-input-form.component.ts
> +                                     });
Почему не в конструкторе ?

2020-10-05 07:34 UTC, FlawlessTheory commented on src/app/components/definition-tab/definition-tab-input-form/definition-tab-input-form.component.ts
> +                                     });
Делал так, как видел в примере на сайте Ангуляра: https://angular.io/guide/reactive-forms#using-the-formbuilder-service-to-generate-controls
Это критично?

2020-10-06 03:10 UTC, nikitamugen approved these changes

2020-10-06 03:10 UTC, nikitamugen commented on src/app/components/definition-tab/definition-tab-input-form/definition-tab-input-form.component.ts
> +                                     });
По большому счет нет. С точки зрения логики это ни на что не влияет.
Но мне привычнее видеть такие вот определения в конструкторе или ngOnInit ну т.е. обернутой функцией.
Просто-напросто чаще всего формы не такие тривиальные. И нужны начальные, предварительно подготовленные, данные. И проще всего, чтобы не мудрить, сделать это в той же функции. Меньше торчащих наружу кишков.

2020-10-06 03:10 UTC, merged